/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: "Thiruvalluvar-Sculpture-1",
    img: [
      "/real products/pa-1.webp",
      "/real products/pa-2.webp",
      "/real products/pa-3.webp",
      "/real products/pa-4.webp",
    ],
    name: "Thiruvalluvar Sculpture",
    price: 1299,
    details:
      "Size: In inches    Height: 9    Width x Depth: 6 x 4    Material: Stone Powder with Resin    Color: Gold, Bronze & Matte Black     Weight (approx.): 2.5 KG ",
    desc: "Thiruvalluvar is of supreme importance in the literary and intellectual fields of Tamil Literature, influencing and inspiring many minds with profound perspectives. Thirukural, a beautiful work of this great poet will be remembered for the pearls of wisdom it has provided to humanity. We, from the team of super-sri are extremely delighted to sculpt the great poet, Thiruvalluvar.",
    discount: 159,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 6,
    category: "GOLD_PLATED_STATUES",
  },
  {
    _id: "Dr.B.R.Ambedkar-Bust-Sculpture-2",
    img: [
      "/real products/pb-1.webp",
      "/real products/pb-2.webp",
      "/real products/pb-3.webp",
      "/real products/pb-4.webp",
    ],
    name: "Dr.B.R.Ambedkar Bust Sculpture",
    price: 2499,
    details:
      "Size: In inches    Height: 8    Width x Depth: 7 x 4    Material: Stone powder and Resin    Color: Antique Bronze, Blue, Gold & Matte Black    Weight (approx): 1.8 KG",
    desc: "A tribute as well as an ode of respect and absolute admiration to the socio-political reformer who charted an insurmountable legacy as a jurist, economist, politician campaigning and fighting against all forms of social discrimination. He eternally stood against tyranny and catapulted India and its people by instilling values of equality and justice.",
    discount: 129,
    addedToCart: false,
    addedToWishlist: false,
    rating: 4,
    size: 12,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Action-Figure-Sculpture-Of-Rocky-Bhai-from-KGF-Universe-3",
    img: [
      "/real products/pc-1.webp",
      "/real products/pc-2.webp",
      "/real products/pc-3.webp",
      "/real products/pc-4.webp",
    ],
    name: "Sculpture Of Rocky Bhai from KGF Universe",
    price: 4499,
    details:
      "Size: In inches Height: 11.5 Width x Depth: 5.5 X 5 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx): 2.340 KG",
    desc: `SuperSri presents to you the perfectly crafted sculpture of the larger-than-life hero, Rocky who stands tall as the undisputed Sultan of the KGF Kingdom. The sculpture helps relive the unbeatable legacy of an iconic cinematic character and his majestic universe, enthralling fans for decades to come.`,
    discount: 179,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 6,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Mustang-Car-Sculpture-from-KGF-Universe-4",
    img: [
      "/real products/pd-1.webp",
      "/real products/pd-2.webp",
      "/real products/pd-3.webp",
      "/real products/pd-4.webp",
    ],
    name: "Mustang Car Sculpture from KGF Universe",
    price: 4500,
    details:
      "Size: In inches Height: 3.5 Width x Depth: 11.5 X 5 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx): 3.160 KG",
    desc: "SuperSri presents to you Rocky’s Mustang which plays an integral part in the amazing action sequences of KGF2 Movie! The high-octane action sequences of the KGF 2 movie were beautifully choreographed and a visual treat. It would be amazing to own the sculpture of the stylish and fantabulous Mustang and cherish the super cool universe of Rocky! Be a proud owner of the movie’s collectibles and flaunt the inner KGF fan in you to the world!",
    discount: 399,
    addedToCart: false,
    addedToWishlist: false,
    rating: 4,
    size: 12,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Mahakavi-Bharathiyar-Sculpture-5",
    img: [
      "/real products/pe-1.webp",
      "/real products/pe-2.webp",
      "/real products/pe-3.webp",
      "/real products/pe-4.webp",
    ],
    name: "Mahakavi Bharathiyar Sculpture",
    price: 1799,
    details:
      "Size: In inches Height: 7 Width x Depth: 4.9 x 4.2 Material: Stone Powder with Resin Color: Antique Bronze & Gold  Weight (approx): 1 KG",
    desc: "C. Subramaniya Bharathiyar was a poet, freedom fighter and social reformer from Tamil Nadu. He was known as Mahakavi Bharathiyar and the laudatory epithet Mahakavi means a great poet. He is considered as one of India’s greatest poets. His songs on nationalism and freedom of India helped to rally the masses to support the Indian Independence Movement in Tamil Nadu.Subramaniya Bharathiyar was born on 11th December 1882, in a village called Ettayapuram in Tirunelveli District in Tamil Nadu and his childhood name was Subbiah. His father was Chinnaswamy Iyer and his mother was Lakshmi Ammal.",
    discount: 399,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 6,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Chhatrapati-Shivaji-Maharaj-Bust-Sculpture-6",
    img: [
      "/real products/pf-1.webp",
      "/real products/pf-2.webp",
      "/real products/pf-3.webp",
      "/real products/pf-4.webp",
    ],
    name: "Chhatrapati Shivaji Maharaj Bust Sculpture",
    price: 3499,
    details: `Size: In inches
Height: 8
Width x Depth: 6 x 5
Material: Stone Powder with Resin
Color: Antique Bronze & Gold
Weight (approx): 2 KG`,
    desc: "super-sri adds to its sculpture collection one of the bravest, progressive, and most sensible rulers of India, Chhatrapati Shivaji. Shivaji established a competent and progressive civil rule with well-structured administrative organizations and was the founder of the Maratha Empire. Shivaji's achievements in administration and various aspects of governance were considered to be the beginning of modern nation-building. Shivaji's Valour, leadership, and warfare strategies will always occupy an important position in the annals of history.",
    discount: 299,
    addedToCart: false,
    addedToWishlist: false,
    rating: 4,
    size: 12,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Olaichuvadi-Valluvar-Sculpture-Illam-Thorum-Valluvar-7",
    img: [
      "/real products/pg-1.webp",
      "/real products/pg-2.webp",
      "/real products/pg-3.webp",
      "/real products/pg-4.webp",
      "/real products/pg-5.webp",
    ],
    name: "Olaichuvadi Valluvar Sculpture Illam Thorum Valluvar",
    price: 999,
    details: `Size: In inches Height: 6 Width x Depth: 3 x 1 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx.): 0.250 KG `,
    desc: "Super-sri presents a sculpture of the towering and magnificent monument of the statue of Thiruvalluvar at Kanyakumari, that symbolises the profound wealth, pleasure and love that can be earned and enjoyed on the foundation of virtue. The statue also portrays the resilience of an ancient poet depicted in a Manuscript, whose words of wisdom will stay forever unshakeable just like his statue which was hit by a powerful tsunami in 2004 and was largely undamaged.",
    discount: 200,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 6,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "MASTER-Thalapathy-Vijay-Bust-Sculpture-8",
    img: [
      "/real products/ph-1.webp",
      "/real products/ph-2.webp",
      "/real products/ph-3.webp",
      "/real products/ph-4.webp",
    ],
    name: "MASTER Thalapathy Vijay Bust Sculpture",
    price: 1499,
    details: `Size: In inches Height: 5 Width x Depth: 4 x 3.5 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx): 350 Grams`,
    desc: "The magnificence and versatile beauty of Thalapathy as a sculpture is unmatchable! We proudly bring to you the sculpture of Thalapthy envisioned and structured with striking intricacy, superlative technical finesse and abundance of love!! The phenomenon of Thalapathy will live on forever through memorable souvenirs and what better way to show our love and admiration than through a beautifully crafted sculpture. Experience the magic of our master with your own hands!",
    discount: 500,
    addedToCart: false,
    addedToWishlist: false,
    rating: 4,
    size: 12,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Kalaignar-Bust-Sculpture-9",
    img: [
      "/real products/pi-1.webp",
      "/real products/pi-2.webp",
      "/real products/pi-3.webp",
      "/real products/pi-4.webp",
    ],
    name: "Kalaignar Bust Sculpture",
    price: 3499,
    details: `Size: In inches Height: 8 Width x Depth: 7 x 4 Material: Stone Powder with Resin Color: Gold Black Glass, Antique Bronze, Matte Black & Gold Weight (approx): 1.8 KG`,
    desc: `Size: In inches Height: 8 Width x Depth: 7 x 4 Material: Stone Powder with Resin Color: Gold Black Glass, Antique Bronze, Matte Black & Gold Weight (approx): 1.8 KG`,
    discount: 1000,
    addedToCart: false,
    addedToWishlist: false,
    rating: 4,
    size: 6,
    category: "GOLD_PLATED_STATUES",
  },
  {
    _id: "Gautama-Buddha-Sculpture-10",
    img: [
      "/real products/pj-1.webp",
      "/real products/pj-2.webp",
      "/real products/pj-3.webp",
      "/real products/pj-4.webp",
      "/real products/pj-5.webp",
      "/real products/pj-6.webp",
    ],
    name: "Gautama Buddha Sculpture",
    price: 3499,
    details: `Size: In Inches Height: 9 Width x Depth: 6 x 4 Material: Stone Powder with Resin Color: Antique Bronze, Gold & Matte Black Weight (approx.): 2.5 KG `,
    desc: "The team of Super-sri presents to you the epitome of enlightenment and the divine being who rediscovered the path to freedom from ignorance, craving, and the cycle of rebirth and suffering. Gautama Buddha was a teacher, philosopher, and spiritual leader who is the founder of Buddhism. Buddha is considered to be the embodiment of love and compassion who constantly inspired his followers to aspire for truth and victory over worldly vanity.",
    discount: 1000,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 12,
    category: "GOLD_PLATED_STATUES",
  },
  {
    _id: "Periyar-Bust-Sculpture-11",
    img: [
      "/real products/pk-1.webp",
      "/real products/pk-2.webp",
      "/real products/pk-3.webp",
      "/real products/pk-4.webp",
      "/real products/pk-5.webp",
      "/real products/pk-6.webp",
    ],
    name: "Periyar Bust Sculpture",
    price: 3330,
    details: `Size: In inches Height: 8 Width x Depth: 7 x 4 Material: Stone Powder with Resin Color: Antique Bronze, Matt Black & Gold Coated Weight (approx.): 2 KG`,
    desc: "The words of Rationalism, Social Justice and Endless fight against Inequality will always resonate in the heart of every individual who deeply relates to Periyar. The Self Respect Movement icon promoted women's empowerment and abolition of caste based discrimination, chronicling an era of growth and development.",
    discount: 1131,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 6,
    category: "MATTE_BLACK_STATUES",
  },
  {
    _id: "J-Jayalalithaa-Bust-Sculpture-12",
    img: [
      "/real products/pl-1.webp",
      "/real products/pl-2.webp",
      "/real products/pl-3.webp",
      "/real products/pl-4.webp",
      "/real products/pl-5.webp",
      "/real products/pl-6.webp",
    ],
    name: "J Jayalalithaa Bust Sculpture",
    price: 3499,
    details: `Size: In inches Height: 8 Width x Depth: 7 x 4 Material: Stone Powder with Resin Color: Gold  Weight (approx): 2.3 KG`,
    desc: "A tribute with heartfelt gratitude to the remarkable and assertive leader who was one of the most influential stateswomen of our country, whose grit and infallible strength was directed towards the upliftment and empowerment of people. The multifaceted legacy of this charismatic and determined icon serves as an inspiration to countless women who want to redefine our country and break the glass ceiling which imposes discrimination and inequality.",
    discount: 1000,
    addedToCart: false,
    addedToWishlist: false,
    rating: 3,
    size: 12,
    category: "GOLD_PLATED_STATUES",
  },
  {
    _id: "Dr.-A.-P.-J-Abdul-Kalam-Bust-Sculpture-13",
    img: [
      "/real products/pm-1.webp",
      "/real products/pm-2.webp",
      "/real products/pm-3.webp",
      "/real products/pm-4.webp",
      "/real products/pm-5.webp",
      "/real products/pm-6.webp",
    ],
    name: "Dr. A.P.J Abdul Kalam Bust Sculpture",
    price: 3499,
    details: `Size: In inches Height: 8 Width x Depth: 7 x 4 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx.): 2 KG`,
    desc: "Super-sri crafts the sculpture of the visionary who helped us realize the value of our dreams, and united our collective consciousness towards achieving any goal with single-minded determination. The sculpture of Dr. A.P.J Abdul Kalam will forever ignite the mind of every individual with the passion to achieve success in their lives through grit and hard work.",
    discount: 1000,
    addedToCart: false,
    addedToWishlist: false,
    rating: 4,
    size: 6,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Karl-Marx-Bust-Sculpture-14",
    img: [
      "/real products/pn-1.webp",
      "/real products/pn-2.webp",
      "/real products/pn-3.webp",
      "/real products/pn-4.webp",
      "/real products/pn-5.webp",
    ],
    name: "Karl Marx Bust Sculpture",
    price: 3600,
    details: `Size: In inches Height: 8 Width x Depth: 6 x 5 Material: Stone Powder with Resin Color: Antique Bronze, Gold, Red Weight (approx): 2 KG`,
    desc: "Super-sri with immense happiness brings to you the sculpture of the radical economist and revolutionary, Karl Marx. The political thoughts and theories of Karl Marx are known as Marxism. Marxism has largely been and will always be the cornerstone of socialist and communist movements across the world.",
    discount: 1199,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 12,
    category: "RED_STATUES",
  },
  {
    _id: "Puneeth-Rajkumar-Bust-Sculpture-15",
    img: [
      "/real products/po-1.webp",
      "/real products/po-2.webp",
      "/real products/po-3.webp",
      "/real products/po-4.webp",
      "/real products/po-5.webp",
      "/real products/po-6.webp",
    ],
    name: "Puneeth Rajkumar Bust Sculpture",
    price: 3499,
    details: `Size: In inches Height: 8 Width x Depth: 7 x 4 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx.): 2 KG`,
    desc: "Super-sri is delighted to sculpt the phenomenal actor, producer, playback singer, philanthropist, and icon Puneeth Rajkumar whose tremendous filmography, charisma, compassion, and immeasurable talent has inspired a legion of his fans fuelling an abundance of love, and fandom that is everlasting and exhilarating.",
    discount: 1000,
    addedToCart: false,
    addedToWishlist: false,
    rating: 4,
    size: 6,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Mahatma-Gandhi-Bust-Sculpture-16",
    img: [
      "/real products/pp-1.webp",
      "/real products/pp-2.webp",
      "/real products/pp-3.webp",
      "/real products/pp-4.webp",
      "/real products/pp-5.webp",
    ],
    name: "Mahatma Gandhi Bust Sculpture",
    price: 3499,
    details: `Size: In inches Height: 8 Width x Depth: 6 x 5 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx): 2 KG`,
    desc: "Super-sri pays tribute to the Mahatma who is venerated throughout the world for his non-violent resistance movement against colonial forces and social inequality, serving as the champion of civil rights, equality, and freedom. Mahatma Gandhi preached the doctrine of truth and ahimsa which serves as an inspiration to countless other revolutionaries and activists across the globe achieving permanent relevance and relatability.",
    discount: 1000,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 12,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Mahabalipuram-Shore-Temple-Sculpture-17",
    img: [
      "/real products/pq-1.webp",
      "/real products/pq-2.webp",
      "/real products/pq-3.webp",
      "/real products/pq-4.webp",
      "/real products/pq-5.webp",
      "/real products/pq-6.webp",
      "/real products/pq-7.webp",
    ],
    name: "Mahabalipuram Shore Temple Sculpture",
    price: 4999,
    details: `Size: In Inches Length: 9.6 Depth: 6.5 Height: 8 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx.): 3 Kg`,
    desc: "Super-sri presents the majestic Mahabalipuram Shore Temple, a landmark architectural marvel of the Pallava Reign to our dear patrons to cherish as memorabilia which has been classified as a UNESCO World Heritage site since 1984. The shore temple signifies religious harmony with sacred spaces dedicated to Shiva and Vishnu and was also an important symbol of Pallava's political and economic strength.",
    discount: 1000,
    addedToCart: false,
    addedToWishlist: false,
    rating: 3,
    size: 6,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Perunthalaivar-Kamarajar-Bust-Sculpture-18",
    img: [
      "/real products/pr-1.webp",
      "/real products/pr-2.webp",
      "/real products/pr-3.webp",
      "/real products/pr-4.webp",
      "/real products/pr-5.webp",
      "/real products/pr-6.webp",
    ],
    name: "Perunthalaivar Kamarajar Bust Sculpture",
    price: 3499,
    details:
      "Size: In inches Height: 8 Width x Depth: 6 x 5 Material: Stone Powder with Resin Color: Antique Bronze, Gold & Matte Black Weight (approx): 1.8 KG",
    desc: "A heartfelt tribute by Super-sri to the man who is synonymous with the selfless public service that he has done to the people of our country, Former Chief Minister Perunthalaivar Kamaraj symbolized an era of stellar leadership and laid the educational, agricultural, and industrial foundations of the state of Tamil Nadu. His legacy is marked by various people-centric reforms and schemes targeted towards the empowerment of underprivileged masses.",
    discount: 1000,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 12,
    category: "MATTE_BLACK_STATUES",
  },
  {
    _id: "Pasumpon-Muthuramalingam-Thevar-Bust-Sculpture-19",
    img: [
      "/real products/ps-1.webp",
      "/real products/ps-2.webp",
      "/real products/ps-3.webp",
      "/real products/ps-4.webp",
      "/real products/ps-5.webp",
      "/real products/ps-6.webp",
    ],
    name: "Pasumpon Muthuramalingam Thevar Bust Sculpture",
    price: 3499,
    details: `Size: In inches Height: 8 Width x Depth: 7 x 4 Material: Stone Powder with Resin Color: Gold Weight (approx): 1.8 KG`,
    desc: "Pasumpon Muthuramalingam Thevar Bust Sculpture made with striking intricacy! ",
    discount: 1000,
    addedToCart: false,
    addedToWishlist: false,
    rating: 3,
    size: 6,
    category: "GOLD_PLATED_STATUES",
  },
  {
    _id: "The-Dravidian-Icons - Table Top - Three-Face-Sculpture-20",
    img: [
      "/real products/pt-1.webp",
      "/real products/pt-2.webp",
      "/real products/pt-3.jpg",
      "/real products/pt-4.jpg",
    ],
    name: "The Dravidian Icons - Table Top - Three Face Sculpture",
    price: 3499,
    details:
      "Size: In inches Height: 4 Width x Depth: 5 x 5 Material: Stone Powder with Resin Color: Antique Bronze ,Matte Black , Gold Weight (approx): 2.5 KG",
    desc: "The pinnacle of glory, exemplary statesmanship, revolutionary movements and era defining social change has been possible due to the path breaking and maverick minds of these three Dravidian icons who have redefined and charted an insurmountable legacy in the growth, development and social justice arena of Tamil Nadu.",
    discount: 1200,
    addedToCart: false,
    addedToWishlist: false,
    rating: 4,
    size: 12,
    category: "MATTE_BLACK_STATUES",
  },
  {
    _id: "Ayyan-Valluvar-Full-Figure-Sculpture-21",
    img: [
      "/real products/pu-1.webp",
      "/real products/pu-2.webp",
      "/real products/pu-3.webp",
      "/real products/pu-4.webp",
      "/real products/pu-5.webp",
      "/real products/pu-6.webp",
      "/real products/pu-7.webp",
      "/real products/pu-8.webp",
    ],
    name: "Ayyan Valluvar Full Figure Sculpture",
    price: 5499,
    details:
      "Size: In inches Height: 12 Width x Depth: 4.5 x 4.5 Material: Stone Powder with Resin Color: Antique Bronze, Matte Black & Gold Weight (approx.): 1.8 KG ",
    desc: "Super-sri presents a sculpture of the towering and magnificent monument of the statue of Thiruvalluvar at Kanyakumari, that symbolises the profound wealth, pleasure and love that can be earned and enjoyed on the foundation of virtue. The statue also portrays the resilience of an ancient poet whose words of wisdom will stay forever unshakeable just like his statue which was hit by a powerful tsunami in 2004 and was largely undamaged.",
    discount: 1000,
    addedToCart: false,
    addedToWishlist: false,
    rating: 3,
    size: 6,
    category: "MATTE_BLACK_STATUES",
  },
  {
    _id: "Arignar-Anna-Bust-Sculpture-22",
    img: [
      "/real products/pv-1.webp",
      "/real products/pv-2.webp",
      "/real products/pv-3.webp",
      "/real products/pv-4.webp",
      "/real products/pv-5.webp",
      "/real products/pv-6.webp",
    ],
    name: "Arignar Anna Bust Sculpture",
    price: 3350,
    details:
      "Size: In inches Height: 8 Width x Depth: 6 x 5 Material: Stone Powder with Resin Color: Antique Bronze, Gold & Matte Black Weight (approx): 1.8 KG",
    desc: "The team of Super-sri presents to you the Stalwart of Dravidian politics, Perarignar anna, the founder of the Dravida Munnetra Kazhagam. An exemplary writer and orator, he has been instrumental in the incomparable growth of the state in many ways and has brought forth a lot of measures to end caste-based discrimination and social inequality.",
    discount: 1199,
    addedToCart: false,
    addedToWishlist: false,
    rating: 4,
    size: 12,
    category: "GOLD_PLATED_STATUES",
  },
  {
    _id: "Dr.-B.-R.-Ambedkar-Full-Figure-Sculpture-23",
    img: [
      "/real products/pw-1.webp",
      "/real products/pw-2.webp",
      "/real products/pw-3.webp",
      "/real products/pw-4.webp",
      "/real products/pw-5.webp",
      "/real products/pw-6.webp",
      "/real products/pw-7.webp",
      "/real products/pw-8.webp",
      "/real products/pw-9.webp",
      "/real products/pw-10.webp",
    ],
    name: "Dr.B.R.Ambedkar Full Figure Sculpture",
    price: 4499,
    details:
      "Size: In inches Height: 10 Width x Depth: 4 x 4 Material: Stone Powder with Resin Color: Antique Bronze & Gold Weight (approx): 1 KG",
    desc: "Super-sri brings to you an iconic sculpture of the multifaceted revolutionary, Dr. Babasaheb Ambedkar who is a social reformer, politician, and crusader against caste and gender-based discrimination. Fondly known as the Architect of the Indian Constitution, his efforts brought about the much-needed change in the socio-cultural landscape of our country striving for dignity, respect, and empowerment for the oppressed sections of the society. The various measures he had envisioned and put forth brought about social, economical, and political growth in our country.",
    discount: 1000,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 6,
    category: "GOLD_PLATED_STATUES",
  },
  {
    _id: "Puratchi-Thalaivar-MGR-Bust-Sculpture-24",
    img: [
      "/real products/px-1.webp",
      "/real products/px-2.webp",
      "/real products/px-3.webp",
      "/real products/px-4.webp",
      "/real products/px-5.webp",
    ],
    name: "Puratchi Thalaivar MGR Bust Sculpture",
    price: 3499,
    details:
      "Size: In inches Height: 8 Width x Depth: 6 x 5 Material: Stone Powder with Resin Color: Gold Black Glass , Antique Bronze  Weight (approx): 1.8 KG",
    desc: "The Formidable and insurmountable politician, a film legend and Bharat Ratna Awardee Puratchi Thalaivar MGR, was a humanitarian icon who will always remain in the hearts of millions immortalized for his inexplicable philanthropy, illustrious filmography, and untiring determination for upliftment and welfare of all people. We, the team of Super-sri are delighted beyond measure to sculpt this charismatic and exemplary icon.",
    discount: 999,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 12,
    category: "GOLD_PLATED_STATUES",
  },
  {
    _id: "Bike-Sculpture-from-KGF-Universe-25",
    img: [
      "/real products/py-1.webp",
      "/real products/py-2.webp",
      "/real products/py-3.webp",
      "/real products/py-4.webp",
      "/real products/py-5.webp",
      "/real products/py-6.webp",
    ],
    name: "Bike Sculpture from KGF Universe",
    price: 5800,
    details:
      "Size: In inches Height: 6.25 Width x Depth: 9.5 X 1.75 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx): 2.14 KG",
    desc: "Super-sri presents to you Rocky’s Bike as a sculpture, which is an important part of his journey from Mumbai to the world of KGF. The iconic scene of Rocky reclaiming Mumbai and unveiling his cherished bike is nostalgic and absolutely adrenaline pumping! Rocky’s bike will definitely be a prized sculpture in the awe-worthy KGF movie Collectibles crafted by Super-sri! Own the movie’s collectibles and flaunt the inner KGF fan in you to the world!",
    discount: 1199,
    addedToCart: false,
    addedToWishlist: false,
    rating: 4,
    size: 6,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Brihadeeswarar-Temple - Thanjai-Periya-Kovil-26",
    img: [
      "/real products/pz-1.webp",
      "/real products/pz-2.webp",
      "/real products/pz-3.webp",
      "/real products/pz-4.webp",
      "/real products/pz-5.webp",
    ],
    name: "Brihadeeswarar Temple - Thanjai Periya Kovil",
    price: 5699,
    details:
      "Size: In inches Height: 8 Width x Depth: 12 x 6 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx): 3.180 kg",
    desc: "The Thanjai Periya Kovil, also known as Brihadeeswarar Temple, is a mesmerizing architectural wonder that stands as a testament to the rich cultural and historical heritage of India. Located in the town of Thanjavur in the southern state of Tamil Nadu, this majestic temple was built by the great Chola king, Raja Raja Chola I, in the 11th century. The temple is dedicated to Lord Shiva and is an iconic symbol of the Chola dynasty's architectural prowess and artistic vision. The Thanjai Periya Kovil (Brihadeeswarar Temple) is not just a magnificent monument but a living testament to the grandeur of the Chola dynasty and the rich cultural heritage of India. By owning a piece from Super-sri's exclusive Thanjai Periya Kovil Sculpture Collection, you can bring the splendor and elegance of this architectural masterpiece into your home or office, celebrating the timeless beauty of one of India's most iconic temples",
    discount: 999,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 12,
    category: "GOLD_PLATED_STATUES",
  },
  {
    _id: "The-Radical-Revolutionaries - Book-Sculpture - B.-R.-Ambedkar-27",
    img: [
      "/real products/pAa-1.webp",
      "/real products/pAa-2.webp",
      "/real products/pAa-3.webp",
      "/real products/pAa-4.webp",
      "/real products/pAa-5.webp",
      "/real products/pAa-6.webp",
    ],
    name: "The Radical Revolutionaries - Book Sculpture - B.R.Ambedkar,",
    price: 899,
    details:
      "Size: In Inches Height: 3 Width x Depth: 2.5 x 05 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx.): 60 Grams",
    desc: "Super-sri presents the Radical Revolutionaries Periyar, Babasaheb Ambedkar and Karl as exquisitely crafted book sculptures which serves as a beautiful symbolic representation of these great icons and the infinite knowledge they gave to the society at large.",
    discount: 299,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 6,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Shirdi-Sai-Baba-Sculpture-28",
    img: [
      "/real products/pAb-1.webp",
      "/real products/pAb-2.webp",
      "/real products/pAb-3.webp",
      "/real products/pAb-4.webp",
      "/real products/pAb-5.webp",
      "/real products/pAb-6.webp",
    ],
    name: "Shirdi Sai Baba Sculpture",
    price: 6299,
    details:
      "Size: In Inches Height : 9 Width : 6 Depth : 6 Material: Stone Powder with Resin Color: Antique Bronze & Gold Weight (approx.): 3.4 Kg",
    desc: "Super-sri brings to you the virtuous spiritual master and saint, Shirdi Sai baba who is seen by many as the eternal symbol of unity between all religions, and taught his followers to never discriminate others based on their identity. He instructed his devotees and followers to lead a moral life, help others, love every living being, and develop two important features of character: faith (Shraddha) and patience (Saburi). Super-sri is humbled beyond measure to bring to our dear patrons a sculpture sculpted flawlessly of a God in human form, spreading love, unconditional kindness and has done miracles that have given eternal hope to humanity.",
    discount: 1399,
    addedToCart: false,
    addedToWishlist: false,
    rating: 3,
    size: 12,
    category: "GOLD_PLATED_STATUES",
  },
  {
    _id: "Hammer-Full-Size-Sculpture-from-KGF-Universe-29",
    img: [
      "/real products/pAc-1.webp",
      "/real products/pAc-2.webp",
      "/real products/pAc-3.webp",
      "/real products/pAc-4.webp",
      "/real products/pAc-5.webp",
      "/real products/pAc-6.webp",
      "/real products/pAc-7.webp",
    ],
    name: "Hammer Full Size Sculpture from KGF Universe",
    price: 5800,
    details:
      "Size: In inches Height: 12 Base : Diameter x Height : 6 X 4.5 Hammer Alone : Width x Depth: 4 X 1.5 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx): 2.14 KG",
    desc: "Rocky was aided by this hammer to reign supreme and capture the kingdom of KGF! The iconic hammer helped Rocky liberate Narachi from the clutches of evil villains. The hammer was the weapon of destruction Rocky used against his adversaries to rebuild an empire filled with richness and glory! Super-sri presents to you the tool of liberation and power, Rocky’s hammer as a sculpture which you can add to the awe-worthy KGF movie collectibles crafted by Super-sri! Own the movie’s collectibles and flaunt the inner KGF fan in you to the world!",
    discount: 899,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 6,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "The-Dravidian-Icons - Three-Face-Sculpture-30",
    img: [
      "/real products/pAd-1.webp",
      "/real products/pAd-2.webp",
      "/real products/pAd-3.webp",
      "/real products/pAd-4.webp",
    ],
    name: "The Dravidian Icons - Three Face Sculpture",
    price: 6299,
    details:
      "Size: In inches Height: 10 Width x Depth: 5 x 5 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx): 2.5 KG",
    desc: "The pinnacle of glory, exemplary statesmanship, revolutionary movements and era defining social change has been possible due to the path breaking and maverick minds of these three Dravidian icons who have redefined and charted an insurmountable legacy in the growth, development and social justice arena of Tamil Nadu.",
    discount: 1499,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 12,
    category: "MATTE_BLACK_STATUES",
  },
  {
    _id: "Thanthai-Periyar-Full-Figure-Sculpture-31",
    img: [
      "/real products/pAe-1.webp",
      "/real products/pAe-2.webp",
      "/real products/pAe-3.webp",
      "/real products/pAe-4.webp",
      "/real products/pAe-5.webp",
      "/real products/pAe-6.webp",
      "/real products/pAe-7.webp",
      "/real products/pAe-8.webp",
      "/real products/pAe-9.webp",
      "/real products/pAe-10.webp",
    ],
    name: "Thanthai Periyar Full Figure Sculpture",
    price: 3300,
    details:
      "Size: In inches Height: 10 Width x Depth: 4 x 4 Material: Stone Powder with Resin Color: Antique Bronze, Matte Black & Gold Weight (approx): 1 KG",
    desc: "Super-sri is delighted to bring to you the iconic sculpture of Periyar who will forever live in the hearts of all individuals who have been inspired by his journey and life. The ideologies of Periyar are irrevocable and intertwined in the cultural fabric of our country. He advocated a politics that stood for Social Equality and Self Respect. The reforms brought about by Periyar were progressive and waged a battle against social, cultural, and gender inequalities, centering his perspectives on rationality and independence.",
    discount: 1200,
    addedToCart: false,
    addedToWishlist: false,
    rating: 4,
    size: 6,
    category: "MATTE_BLACK_STATUES",
  },
  {
    _id: "Che-Guevara-Sculpture-32",
    img: [
      "/real products/pAf-1.webp",
      "/real products/pAf-2.webp",
      "/real products/pAf-3.webp",
      "/real products/pAf-4.webp",
      "/real products/pAf-5.webp",
      "/real products/pAf-6.webp",
      "/real products/pAf-7.webp",
      "/real products/pAf-8.webp",
      "/real products/pAf-9.webp",
      "/real products/pAf-10.webp",
    ],
    name: "Che Guevara Sculpture",
    price: 3499,
    details:
      "Size: In inches Height: 8 Width x Depth: 6 x 4 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx): 1.56 KG ",
    desc: "Che Guevara, A famous revolutionary leader who fought for social justice and equality. He played a pivotal role in the Cuban Revolution and became an icon for many who sought change and resistance against oppressive systems. He fought against imperialism, capitalism, and inequality, and his image has come to symbolize rebellion and resistance. Super-sri is proud to honor Che Guevara's legacy with a stunning sculpture, that captures his spirit and impact. This sculpture is a tribute to a visionary leader who inspired a generation and continues to resonate today.",
    discount: 999,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 12,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Dodamma-Gun-Sculpture-from-KGF-Universe-33",
    img: [
      "/real products/pAg-1.webp",
      "/real products/pAg-2.webp",
      "/real products/pAg-3.webp",
      "/real products/pAg-4.webp",
      "/real products/pAg-5.webp",
      "/real products/pAg-6.webp",
      "/real products/pAg-7.webp",
      "/real products/pAg-8.webp",
      "/real products/pAg-9.webp",
    ],
    name: "Dodamma Gun Sculpture from KGF Universe",
    price: 5800,
    details:
      "Size: In inches Height: 10 Width x Depth: 9.5 X 1.75 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx): 2.1 KG",
    desc: "The Godfather of all large guns, the Dodamma is an M1919 American Made Browning Machine Gun. Rocky with absolute style takes this gun for a field visit and creates one of the most memorable scenes in Indian cinematic history. The gun goes blaring, captivating the audience completely with wonder and amazement at the force and strength of this gun which is an absolute marvel. Rocky’s Gun will definitely be a prized sculpture in the awe-worthy KGF movie Collectibles crafted by Super-sri! Own the movie’s collectibles and flaunt the inner KGF fan in you to the world!",
    discount: 1199,
    addedToCart: false,
    addedToWishlist: false,
    rating: 3,
    size: 6,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "V.-O.-Chidambaram-Bust-Sculpture-34",
    img: [
      "/real products/pAh-1.webp",
      "/real products/pAh-2.webp",
      "/real products/pAh-3.webp",
      "/real products/pAh-4.webp",
      "/real products/pAh-5.webp",
      "/real products/pAh-6.webp",
      "/real products/pAh-7.webp",
    ],
    name: "V.O.Chidambaram Bust Sculpture",
    price: 3499,
    details:
      "Size: In inches Height: 8 Width x Depth: 6 x 5 Material: Stone Powder with Resin Color: Antique Bronze, Gold & Matte Black Weight (approx): 1.8 KG ",
    desc: "Super-sri celebrates the formidable freedom fighter, revolutionary and entrepreneur V.O.Chidambaram as a sculpture. Famously known as Kappalottiya Tamizhan, he started the Swadeshi Steam Navigation Company to compete against the monopoly of the British and was respected for the sacrifices that he has done for the nation.",
    discount: 999,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 12,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "The-Radical-Revolutionaries - Table Top - Three-Face-Sculpture-35",
    img: [
      "/real products/pAi-1.webp",
      "/real products/pAi-2.webp",
      "/real products/pAi-3.webp",
      "/real products/pAi-4.webp",
      "/real products/pAi-5.webp",
    ],
    name: "The Radical Revolutionaries - Table Top - Three Face Sculpture",
    price: 3499,
    details:
      "Size: In inches Height: 4 Width x Depth: 5 x 5 Material: Stone Powder with Resin Color: Antique Bronze , Gold & Matte Black Weight (approx): 2.5 KG",
    desc: "Super-sri presents the Radical Revolutionaries Periyar, Babasaheb Ambedkar and Karl Marx coming together as a sculpture crafted exquisitely for the ardent followers and individuals inspired by these icons who tirelessly fought for reclaiming self-respect, social justice and equality for the marginalised and vulnerable sections of society.",
    discount: 899,
    addedToCart: false,
    addedToWishlist: false,
    rating: 4,
    size: 6,
    category: "GOLD_PLATED_STATUES",
  },
  {
    _id: "Thambi-Sculpture-36",
    img: [
      "/real products/pAj-1.webp",
      "/real products/pAj-2.webp",
      "/real products/pAj-3.webp",
      "/real products/pAj-4.webp",
      "/real products/pAj-5.webp",
    ],
    name: "Thambi Sculpture",
    price: 1299,
    details:
      "Size: In inches Height: 8 Width x Depth: 2.8 x 2.4 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx): 0.46 KG",
    desc: "Super-sri presents the official Mascot Thambi sculpture for the 44th FIDE Chess Olympiad, Created in collaboration with the Tamilnadu Government. Thambi is a symbol of the prestigious international chess event held in Chennai in 2022. The sculpture was presented by the Honourable Prime Minister Narendra Modi to all the Winners of Chess Olympiad, adding to its already impressive credentials. Now, fans of chess and art enthusiasts alike can own a piece of history with the Thambi sculpture. Crafted with Super-sri's signature attention to detail and expert craftsmanship, this sculpture is a testament to the beauty and elegance of chess as a sport. Whether you're a seasoned chess player or simply appreciate the artistry of sculpture, the Thambi sculpture is a must-have addition to any collection.Order your Mascot Thambi sculpture today and celebrate the legacy of the 44th FIDE Chess Olympiad for years to come.",
    discount: 399,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 12,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Y.-S.-Rajasekhara-Sculpture-37",
    img: [
      "/real products/pAk-1.webp",
      "/real products/pAk-2.webp",
      "/real products/pAk-3.webp",
      "/real products/pAk-4.webp",
      "/real products/pAk-5.webp",
      "/real products/pAk-6.webp",
      "/real products/pAk-7.webp",
      "/real products/pAk-8.webp",
    ],
    name: "Y. S. Rajasekhara Sculpture",
    price: 3499,
    details:
      "Size: In inches Height: 8 Width x Depth: 6 x 4 Material: Stone Powder with Resin Color: Antique Bronze & Gold Weight (approx): 1.74 KG",
    desc: "Y.S. Rajasekhara, popularly known as YSR, was a prominent leader and Former Chief Minister of Andhra Pradesh. He is remembered for his significant contributions towards the welfare and development of his state. His policies and initiatives in the areas of healthcare, education, and agriculture have had a profound impact on the people of Andhra Pradesh. To commemorate his legacy and pay tribute to his contributions, Super-sri presents a stunning sculpture of YSR that captures his essence and charisma. Crafted with intricate details and skillful artistry, this sculpture depicts YSR in a dignified and thoughtful pose, with his signature smile and warm gaze.The intricately designed sculpture captures the essence of his persona, and serves as a fitting tribute to a great leader who has left an indelible mark on the people of Andhra Pradesh and beyond.",
    discount: 999,
    addedToCart: false,
    addedToWishlist: false,
    rating: 3,
    size: 6,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Replica-of-Kalari-Sculpture-from-Moovar-Temple-38",
    img: [
      "/real products/pAl-1.webp",
      "/real products/pAl-2.webp",
      "/real products/pAl-3.webp",
      "/real products/pAl-4.webp",
      "/real products/pAl-5.webp",
      "/real products/pAl-6.webp",
    ],
    name: "Replica of Kalari Sculpture from Moovar Temple",
    price: 3499,
    details:
      "Size: In inches Height: 8 Width x Depth: 5 x 2 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx): 1.40 KG",
    desc: "A stunning replica of the Kalari sculpture from the Moovar temple! This exquisite sculpture is a true masterpiece of the Irukkuvel period, showcasing the unparalleled artistic skills of the ancient craftsmen. The sculpture depicts Lord Shiva in a fierce yet graceful posture, standing triumphantly over a defeated Yama (Kala). Shiva's dance of destruction, known as the Tandava, is believed to represent the cycle of creation and destruction that governs the universe.The attention to detail in this sculpture is truly remarkable. Every intricate feature, from the delicate facial expressions to the intricate clothing and jewelry, has been carefully crafted to perfection. The sculpture captures the essence of the ancient Kalari tradition and brings it to life in stunning detail.This exquisite piece of art is not only a testament to the rich cultural heritage of India, but also a stunning addition to any home or office. Don't miss the chance to own this incredible work of art. Order your very own replica of the Kalari sculpture from the Moovar temple today and experience the magic of ancient Indian art right in your own home.",
    discount: 989,
    addedToCart: false,
    addedToWishlist: false,
    rating: 4,
    size: 12,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Olaichuvadi-Valluvar-Sculpture-39",
    img: [
      "/real products/pAm-1.webp",
      "/real products/pAm-2.webp",
      "/real products/pAm-3.webp",
      "/real products/pAm-4.webp",
      "/real products/pAm-5.webp",
      "/real products/pAm-6.webp",
    ],
    name: "Olaichuvadi Valluvar Sculpture",
    price: 3499,
    details:
      "Size: In inches Height: 9 Width x Depth: 4.5 x 1.6 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx.): 0.6 KG ",
    desc: "Super-sri presents a sculpture of the towering and magnificent monument of the statue of Thiruvalluvar at Kanyakumari, that symbolises the profound wealth, pleasure and love that can be earned and enjoyed on the foundation of virtue. The statue also portrays the resilience of an ancient poet depicted in a Manuscript, whose words of wisdom will stay forever unshakeable just like his statue which was hit by a powerful tsunami in 2004 and was largely undamaged.",
    discount: 1199,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 6,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Perasiriyar-Anbazhagan-Sculpture-40",
    img: [
      "/real products/pAn-1.webp",
      "/real products/pAn-2.webp",
      "/real products/pAn-3.webp",
      "/real products/pAn-4.webp",
      "/real products/pAn-5.webp",
    ],
    name: "Perasiriyar Anbazhagan Sculpture",
    price: 3499,
    details:
      "Size: In inches Height: 8 Width x Depth: 6 x 4 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx): 1.8 KG",
    desc: "Perasiriyar Anbazhagan, a true pioneer in the field of social justice, and we are honored to be able to bring his legacy to life through our sculpture. Anbazhagan's story is one of courage, determination, and a relentless pursuit of justice. He dedicated his life to fighting for the rights of the oppressed and underprivileged, and his legacy continues to inspire us today",
    discount: 899,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 12,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Kalaignar-Pen-Sculpture-41",
    img: [
      "/real products/pAo-1.webp",
      "/real products/pAo-2.webp",
      "/real products/pAo-3.webp",
      "/real products/pAo-4.webp",
    ],
    name: "Kalaignar Pen Sculpture",
    price: 2499,
    details:
      "Size: In Inches Height: 12 Pen Thickness: 1 Pedestal Diameter: 4.25 Material: Stone Powder with Resin Color: Antique Bronze Weight (approx.): 600 Grams",
    desc: `"Kalaignar Karunanidhi Pen Sculpture" – A Masterpiece Tribute to a Remarkable Leader The Kalaignar Pen Sculpture, is a tribute to a man who left an indelible mark on Indian politics and society. Honouring the legacy of the renowned writer and leader, this pen sculpture is more than just a piece of art; it is a testament to the enduring spirit of Kalaignar Karunanidhi.This pen sculpture encapsulates the essence of Kalaignar Karunanidhi's inspiring persona. His leadership, dedication to public service, and profound literary contributions are symbolized in this unique piece. The pen, a tool he used to inspire millions, serves as a fitting metaphor for his significant influence.The Kalaignar Karunanidhi Pen Sculpture is more than just an aesthetic addition to your space. It is an embodiment of inspiration, encouraging the beholder to appreciate the value of leadership and the power of written words."`,
    discount: 899,
    addedToCart: false,
    addedToWishlist: false,
    rating: 2,
    size: 6,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  {
    _id: "Ashoka-Pillar-Sculpture-42",
    img: [
      "/real products/pAp-1.webp",
      "/real products/pAp-2.webp",
      "/real products/pAp-3.webp",
      "/real products/pAp-4.webp",
      "/real products/pAp-5.webp",
      "/real products/pAp-6.webp",
      "/real products/pAp-7.webp",
      "/real products/pAp-8.webp",
      "/real products/pAp-9.webp",
    ],
    name: "Ashoka Pillar Sculpture",
    price: 1499,
    details:
      "Size: In Inches Height: 5 Diameter : 2.1 Material: Stone Powder with Resin Color: Antique Bronze & Gold Weight (approx.): 200 Grams",
    desc: "The team of Super-sri presents to you India's national symbol, The Ashoka Pillar which serves as the perfect confluence of Ancient India and our Modern Republic that has the shared values of peace, justice, and tolerance. The Ashoka Pillar was erected by one of the greatest emperors of India, Emperor Ashoka. The Ashoka Pillar was adopted as the National Emblem of India on 26 January 1950, the day India became a Republican Nation, and thereafter it was embedded in the Indian currency. The Ashoka pillar which has been adopted as the National Emblem will always serve as the depiction of the eternal and universal power of righteousness and truth.",
    discount: 199,
    addedToCart: false,
    addedToWishlist: false,
    rating: 5,
    size: 12,
    category: "ANTIQUE_BRONZE_STATUES",
  },
  // {
  //   _id: "",
  //   img: [],
  //   name: "",
  //   price: 3499,
  //   details: ``,
  //   desc: "",
  //   discount: 299,
  //   addedToCart: false,
  // addedToWishlist : false,
  // },
];
